This is my testing ground, named after the SpaceX testing ground in Texas. I use it to test stuff that I'm not sure about, which usually involves the dimensions of matrices resulting from tf-ops.

In [30]:
import tensorflow as tf
import numpy as np

n = 5
d = 3

x = tf.constant(np.reshape(np.arange(n),[n,1]), dtype=tf.float32)
coefficients = tf.constant(np.reshape(np.arange(n*d),[n,d]), dtype=tf.float32)
summe = tf.constant(np.zeros((5,1)), dtype=tf.float32)
for i in range(d):
    summe += tf.multiply(tf.math.pow(x,tf.constant(i, dtype=tf.float32)), tf.reshape(coefficients[:,i], [n,1]))

with tf.Session() as sess:
    _x, _co, _sum = sess.run([x,coefficients,summe])
    print(_x)
    print(_co)
    print(_sum)

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]
[[  0.]
 [ 12.]
 [ 52.]
 [138.]
 [288.]]


In [34]:
import tensorflow as tf

a = tf.constant(np.ones((32)), dtype=tf.float32)
b = tf.constant(np.ones((32))*3, dtype=tf.float32)
res = tf.multiply(a,b)

with tf.Session() as sess:
    _res = sess.run(res)
    print(_res)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3.]
